require("fburguer.plugins-setup")
require("fburguer.core.options")
require("fburguer.core.keymaps")
require("fburguer.core.colorscheme")
require("fburguer.plugins.comment")
require("fburguer.plugins.nvim-tree")
require("fburguer.plugins.lualine")
require("fburguer.plugins.telescope")
require("fburguer.plugins.nvim-cmp")
require("fburguer.plugins.lsp.mason")
require("fburguer.plugins.flutter-tools")
--:require("fburguer.plugins.lsp.lspsaga")
require("fburguer.plugins.lsp.lspconfig")
require("fburguer.plugins.lsp.null-ls")

